version: "3.7"

x-buildargs: &build_args
  GIT_COMMIT: ${GIT_COMMIT:-'git-commit'}
  BUILD_VERSION: ${BUILD_VERSION:-'semver'}

services:
  ui:
    image: ${CR_BASE:-ghcr.io/implex1v}/pwgen-ui:${BUILD_VERSION:-latest}
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
    - api
    build:
      context: ./ui/
      args:
        <<: *build_args

  api:
    image: ${CR_BASE:-ghcr.io/implex1v}/pwgen-api:${BUILD_VERSION:-latest}
    restart: unless-stopped
    ports:
      - 8080:8080
    build: 
      context: ./api/
      args:
        <<: *build_args
