name: api
on:
  push:
    branches:
      - main
    paths:
      - "api/**"
  workflow_dispatch:
    
jobs:
  version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: version
        run: |
          echo "VERSION=$(curl -Ls https://solugo.github.io/gitversion/run.sh | ARGS='./ -c ${{ inputs.component }} --dirty_ignore' bash)" >> $GITHUB_OUTPUT
    
  build:
    uses: Implex1v/pwgen/.github/workflows/_build.yml@main
    needs:
    - version
    with:
      version: ${{ needs.version.outputs.version }}
      component: api
    secrets:
      cr: ${{ secrets.CR }}
      cr_token: ${{ secrets.GITHUB_TOKEN }}
      cr_user: ${{ secrets.CR_USER }}

  deploy:
    uses: Implex1v/pwgen/.github/workflows/_deploy.yml@main
    needs:
    - version
    - build
    with:
      version: "${{ needs.version.outputs.version }}"
      component: api
    secrets:
      cr: ${{ secrets.CR }}
      cr_token: ${{ secrets.GITHUB_TOKEN }}
      cr_user: ${{ secrets.CR_USER }}
      domain: ${{ secrets.BASE_DOMAIN }}
      kube_config: ${{ secrets.KUBE_CONFIG }}
