name: ui
on:
  push:
    branches:
      - main
    paths:
      - "ui/**"
  workflow_dispatch:
    
jobs:
  version:
    runs-on: ubuntu-22.04
    outputs:
      semver: ${{ steps.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: version
        name: Version
        run: |
          ls -la
          curl https://github.com/solugo/gitversion/releases/latest/download/gitversion-linux-x64 -Lso gitversion
          chmod a+x gitversion
          ./gitversion ./ -c ui --dirty_ignore
          echo "$(./gitversion ./ -c ui --dirty_ignore)"
          echo "VERSION=$(./gitversion ./ -c ui --dirty_ignore)" >> $GITHUB_OUTPUT

  build:
    uses: Implex1v/pwgen/.github/workflows/_build.yml@main
    needs:
    - version
    with:
      version: ${{ needs.version.outputs.semver }}
      component: ui
    secrets:
      cr: ${{ secrets.CR }}
      cr_token: ${{ secrets.GITHUB_TOKEN }}
      cr_user: ${{ secrets.CR_USER }}

  deploy:
    uses: Implex1v/pwgen/.github/workflows/_deploy.yml@main
    needs:
    - version
    - build
    with:
      version: "${{ needs.version.outputs.semver }}"
      component: ui
    secrets:
      cr: ${{ secrets.CR }}
      cr_token: ${{ secrets.GITHUB_TOKEN }}
      cr_user: ${{ secrets.CR_USER }}
      domain: ${{ secrets.BASE_DOMAIN }}
      kube_config: ${{ secrets.KUBE_CONFIG }}
